language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
cache: yarn
script:
  - yarn bootstrap
  - cd packages/rocketact-scripts/test/fixture/simple/
  - yarn
  - cd -
  - yarn build
  - yarn test
