language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
cache: yarn
script:
  - yarn bootstrap
  - cd packages/rocketact-scripts/test/fixture/simple/
  - yarn
  - cd -
  - yarn build
  - yarn test
